spring:
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/book_review_db
    username: prod_user  # Вставьте безопасные данные для пользователя
    password: prod_password  # Задайте безопасный пароль

  jpa:
    hibernate:
      ddl-auto: none  # В продакшене не меняем структуру базы данных
    show-sql: false  # Отключаем вывод SQL запросов для повышения безопасности

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  ssl:
    enabled: true  # Настройка для HTTPS
    key-store: classpath:keystore.p12
    key-store-password: secure_password  # Укажите пароль для ключевого хранилища
    key-store-type: PKCS12
    key-alias: tomcat
