spring:
  datasource:
    url: ${AWS_DB_URL}
    username: ${AWS_DB_USERNAME}
    password: ${AWS_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    org.springframework.boot.context.properties: debug