spring:
  datasource:
    url: jdbc:postgresql://database-bookreviews.cj48eu08k1d5.eu-north-1.rds.amazonaws.com:5432/book_review_db
    username: postgres
    password: fdre&7rd^654

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false