server:
  port: 8080

spring:
  application:
    name: book-review-app
  profiles:
    active: local
  flyway:
    enabled: true
    locations: classpath:db/migration
  threads:
    virtual:
      enabled: true

logging:
  level:
    root: INFO