#name: Deploy to Production
#
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out repository
#        uses: actions/checkout@v4
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Log in to Amazon ECR
#        uses: aws-actions/amazon-ecr-login@v1
#
#      - name: Build Docker image
#        run: |
#          docker build -t ${{ secrets.AWS_ECR_REPOSITORY_NAME }} .
#
#      - name: Tag Docker image
#        run: |
#          docker tag ${{ secrets.AWS_ECR_REPOSITORY_NAME }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY_NAME }}:latest
#
#      - name: Push Docker image to ECR
#        run: |
#          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY_NAME }}:latest

