name: Deploy to Amazon ECS

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_REGISTRY: ${{ secrets.AWS_ECR }}
  AWS_REPOSITORY: bookreviewsrepository

jobs:
  deploy:
    name: Deploy
    if: ${{ github.event.workflow_run.head_branch == 'master' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          echo "AWS_DB_URL=${{ secrets.AWS_DB_URL }}" >> $GITHUB_ENV
          echo "AWS_DB_USERNAME=${{ secrets.AWS_DB_USERNAME }}" >> $GITHUB_ENV
          echo "AWS_DB_PASSWORD=${{ secrets.AWS_DB_PASSWORD }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $AWS_REGION

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag and push image to Amazon ECR
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_REGISTRY
          docker build -t $AWS_REPOSITORY:$IMAGE_TAG .
          docker tag $AWS_REPOSITORY:$IMAGE_TAG $AWS_REGISTRY/$AWS_REPOSITORY:$IMAGE_TAG
          docker push $AWS_REGISTRY/$AWS_REPOSITORY:$IMAGE_TAG